export enum EAttackTypes {
    BOTNET = "Botnet",
    BRUTE_FORCE = "Brute Force",
    CREDENTIAL_STUFFING = "Credential Stuffing",
    CSRF = "CSRF",
    DOS = "DoS",
    DDOS = "DDoS",
    DNS_SPOOFING = "DNS Spoofing",
    MALWARE = "Malware",
    MAN_IN_THE_MIDDLE = "Man-in-the-Middle",
    PHISHING = "Phishing",
    PORT_SCANNING = "Port Scanning",
    RANSOMWARE = "Ransomware",
    SQL_INJECTION = "SQL Injection",
    SSRF = "SSRF",
    XSS = "XSS",
    ZERO_DAY = "Zero Day",
}