export enum EAttackTypes {
    APT = "APT",
    BOTNET = "BOTNET",
    BRUTE_FORCE = "BRUTE_FORCE",
    CREDENTIAL_STUFFING = "CREDENTIAL_STUFFING",
    CSRF = "CSRF",
    DOS = "DOS",
    DDOS = "DDOS",
    DNS_SPOOFING = "DNS_SPOOFING",
    INSIDER_THREAT = "INSIDER_THREAT",
    MALWARE = "MALWARE",
    MALWARE_C2_BEACON = "MALWARE_C2_BEACON",
    MAN_IN_THE_MIDDLE = "MAN_IN_THE_MIDDLE",
    PATH_TRAVERSAL = "PATH_TRAVERSAL",
    PHARMING = "PHARMING",
    PHISHING = "PHISHING",
    PORT_SCANNING = "PORT_SCANNING",
    RANSOMWARE = "RANSOMWARE",
    RCE = "RCE",
    SQL_INJECTION = "SQL_INJECTION",
    SSRF = "SSRF",
    SYN_FLOOD = "SYN_FLOOD",
    XSS = "XSS",
    ZERO_DAY = "ZERO_DAY",
}

export const attackTypeLabels: Record<EAttackTypes, string> = {
    [EAttackTypes.APT]: "APT",
    [EAttackTypes.BOTNET]: "Botnet",
    [EAttackTypes.BRUTE_FORCE]: "Brute Force",
    [EAttackTypes.CREDENTIAL_STUFFING]: "Credential Stuffing",
    [EAttackTypes.CSRF]: "CSRF",
    [EAttackTypes.DOS]: "DoS",
    [EAttackTypes.DDOS]: "DDoS",
    [EAttackTypes.DNS_SPOOFING]: "DNS Spoofing",
    [EAttackTypes.INSIDER_THREAT]: "Insider Threat",
    [EAttackTypes.MALWARE]: "Malware",
    [EAttackTypes.MALWARE_C2_BEACON]: "Malware C2 Beacon",
    [EAttackTypes.MAN_IN_THE_MIDDLE]: "Man-in-the-Middle",
    [EAttackTypes.PATH_TRAVERSAL]: "Path Traversal",
    [EAttackTypes.PHARMING]: "Pharming",
    [EAttackTypes.PHISHING]: "Phishing",
    [EAttackTypes.PORT_SCANNING]: "Port Scanning",
    [EAttackTypes.RANSOMWARE]: "Ransomware",
    [EAttackTypes.RCE]: "RCE",
    [EAttackTypes.SQL_INJECTION]: "SQL Injection",
    [EAttackTypes.SSRF]: "SSRF",
    [EAttackTypes.SYN_FLOOD]: "SYN Flood",
    [EAttackTypes.XSS]: "XSS",
    [EAttackTypes.ZERO_DAY]: "Zero Day",
};

export function getAttackTypeLabel(type: EAttackTypes): string {
    return attackTypeLabels[type] || "Unknown";
}