name: CI Check
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
jobs:
  backend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Cài đặt dependencies
        run: npm ci

      - name: Kiểm tra Lint
        run: npm run lint --if-present

      - name: Chạy Unit Test
        run: npm test --if-present
  frontend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4
        
      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Cài đặt dependencies
        run: npm ci

      - name: Kiểm tra Lint
        run: npm run lint --if-present

      - name: Chạy Unit Test
        run: npm test --if-present
